// Generated by packages/auth/scripts/generate-schema.ts -- do not edit.
// Run `bun run auth:generate` in @repo/auth after changing the auth config.

import { index, pgTable, text, timestamp } from "drizzle-orm/pg-core";
import { newId } from "../id";
import { user } from "./users";

/**
 * Credentials and linked providers, one row per (providerId, accountId).
 *
 * `password` holds the Argon2id hash for email/password sign-in -- the column is
 * nullable because OAuth accounts have none. The OAuth token columns are the
 * mirror case: null for password accounts.
 */
export const account = pgTable(
  "account",
  {
    accessToken: text("access_token"),
    accessTokenExpiresAt: timestamp("access_token_expires_at", {
      withTimezone: true,
    }),
    accountId: text("account_id").notNull(),
    createdAt: timestamp("created_at", { withTimezone: true })
      .defaultNow()
      .notNull(),
    id: text("id").primaryKey().$defaultFn(newId),
    idToken: text("id_token"),
    issuer: text("issuer"),
    password: text("password"),
    providerId: text("provider_id").notNull(),
    refreshToken: text("refresh_token"),
    refreshTokenExpiresAt: timestamp("refresh_token_expires_at", {
      withTimezone: true,
    }),
    scope: text("scope"),
    updatedAt: timestamp("updated_at", { withTimezone: true })
      .$onUpdate(() => /* @__PURE__ */ new Date())
      .notNull(),
    userId: text("user_id")
      .notNull()
      .references(() => user.id, { onDelete: "cascade" }),
  },
  (table) => [
    index("account_userId_idx").on(table.userId),
    /*
     * The OAuth sign-in lookup: Better Auth resolves an account by
     * (providerId, accountId) on every callback. Leading with providerId makes
     * the index usable for "all accounts of this provider" too, which the
     * reverse order would not.
     */
    index("account_provider_account_idx").on(table.providerId, table.accountId),
  ]
);
