// Generated by packages/auth/scripts/generate-schema.ts -- do not edit.

import { relations } from "drizzle-orm";
import { account } from "./accounts";
import { session } from "./sessions";
import { user } from "./users";

/**
 * Relations live apart from the tables on purpose.
 *
 * `userRelations` needs `session` and `account`, and both of those need `user`.
 * Declaring them beside the tables makes users.ts and sessions.ts import each
 * other; Drizzle's lazy callbacks survive that cycle, but it is a cycle a future
 * edit can easily break.
 */
export const userRelations = relations(user, ({ many }) => ({
  accounts: many(account),
  sessions: many(session),
}));

export const sessionRelations = relations(session, ({ one }) => ({
  user: one(user, {
    fields: [session.userId],
    references: [user.id],
  }),
}));

export const accountRelations = relations(account, ({ one }) => ({
  user: one(user, {
    fields: [account.userId],
    references: [user.id],
  }),
}));
