// Generated by packages/auth/scripts/generate-schema.ts -- do not edit.
// Run `bun run auth:generate` in @repo/auth after changing the auth config.

import { index, pgTable, text, timestamp } from "drizzle-orm/pg-core";
import { newId } from "../id";
import { user } from "./users";

/**
 * Active sessions. `token` is what the client presents; it is unique and
 * indexed by that constraint, and `user_id` carries its own index because every
 * session lookup filters on it.
 *
 * `onDelete: "cascade"` is load-bearing: deleting a user must not strand sessions
 * that would otherwise still authenticate.
 */
export const session = pgTable(
  "session",
  {
    createdAt: timestamp("created_at", { withTimezone: true })
      .defaultNow()
      .notNull(),
    expiresAt: timestamp("expires_at", { withTimezone: true }).notNull(),
    id: text("id").primaryKey().$defaultFn(newId),
    ipAddress: text("ip_address"),
    token: text("token").notNull().unique(),
    updatedAt: timestamp("updated_at", { withTimezone: true })
      .$onUpdate(() => /* @__PURE__ */ new Date())
      .notNull(),
    userAgent: text("user_agent"),
    userId: text("user_id")
      .notNull()
      .references(() => user.id, { onDelete: "cascade" }),
  },
  (table) => [index("session_userId_idx").on(table.userId)]
);
