// Generated by packages/auth/scripts/generate-schema.ts -- do not edit.
// Run `bun run auth:generate` in @repo/auth after changing the auth config.

import { sql } from "drizzle-orm";
import { boolean, pgTable, text, timestamp, uuid } from "drizzle-orm/pg-core";
import { newId } from "../id";

/**
 * The account owner. The export is named `user`, singular, because that is the
 * model name Better Auth's Drizzle adapter looks up -- renaming it to `users`
 * would require an explicit mapping in `drizzleAdapter`.
 */
export const user = pgTable("user", {
  avatarUrl: text("avatar_url"),
  bannerUrl: text("banner_url"),
  createdAt: timestamp("created_at", { withTimezone: true })
    .defaultNow()
    .notNull(),
  displayUsername: text("display_username"),
  email: text("email").notNull().unique(),
  emailVerified: boolean("email_verified").default(false).notNull(),
  id: uuid("id").primaryKey().$defaultFn(newId).default(sql`uuidv7()`),
  image: text("image"),
  name: text("name").notNull(),
  updatedAt: timestamp("updated_at", { withTimezone: true })
    .defaultNow()
    .$onUpdate(() => /* @__PURE__ */ new Date())
    .notNull(),
  username: text("username").unique(),
});
