// Generated by packages/auth/scripts/generate-schema.ts -- do not edit.
// Run `bun run auth:generate` in @repo/auth after changing the auth config.

import { sql } from "drizzle-orm";
import { index, pgTable, text, timestamp, uuid } from "drizzle-orm/pg-core";
import { newId } from "../id";

/**
 * Short-lived tokens for email verification, password reset and magic links.
 *
 * Nothing references this table, so it has no foreign key -- expired rows are safe
 * to prune on a schedule.
 */
export const verification = pgTable(
  "verification",
  {
    createdAt: timestamp("created_at", { withTimezone: true })
      .defaultNow()
      .notNull(),
    expiresAt: timestamp("expires_at", { withTimezone: true }).notNull(),
    id: uuid("id").primaryKey().$defaultFn(newId).default(sql`uuidv7()`),
    identifier: text("identifier").notNull(),
    updatedAt: timestamp("updated_at", { withTimezone: true })
      .defaultNow()
      .$onUpdate(() => /* @__PURE__ */ new Date())
      .notNull(),
    value: text("value").notNull(),
  },
  (table) => [
    index("verification_identifier_idx").on(table.identifier),
    /*
     * Consuming a token matches identifier AND value together. The single
     * identifier index above still serves the cleanup query that prunes every
     * token for an address.
     */
    index("verification_identifier_value_idx").on(
      table.identifier,
      table.value
    ),
  ]
);
